# Generated by Django 5.0.6 on 2024-07-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_civilstatus_item_civil_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='email',
            new_name='favorite_position',
        ),
        migrations.AddField(
            model_name='item',
            name='favorite_website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gmail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='guardian_contact_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='guardian_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_of_favorite_tita',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
