# Generated by Django 5.0.6 on 2024-07-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_birthday_item_birthdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='birthdate',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='favorite_position',
            new_name='blood_type',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='favorite_website',
            new_name='citizenship',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='guardian_contact_number',
            new_name='sss_number',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='guardian_name',
            new_name='tin_number',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name_of_favorite_tita',
            new_name='zip_code',
        ),
    ]
