# Generated by Django 5.0.6 on 2024-07-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_birthdate_item_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='gmail',
            new_name='email',
        ),
    ]
